products = [
  # Toyota Cars
  {
    '_id': '1',
    'name': 'Toyota Camry',
    'brand': 'Toyota',
    'category': 'Sedan',
    'price': 24999.99,
    'countInStock': 15,
    'rating': 4.7,
    'numReviews': 18,
    'description': 'The Toyota Camry is a midsize car that offers a comfortable and spacious interior, advanced safety features, and fuel efficiency.',
    'image': '/images/camry.jpg',
  },
  {
    '_id': '2',
    'name': 'Toyota Prius',
    'brand': 'Toyota',
    'category': 'Hybrid',
    'price': 27999.99,
    'countInStock': 12,
    'rating': 4.5,
    'numReviews': 15,
    'description': 'The Toyota Prius is a hybrid car known for its exceptional fuel efficiency and eco-friendly features. It\'s a popular choice for environmentally conscious drivers.',
    'image': '/images/prius.jpg',
  },
  {
    '_id': '3',
    'name': 'Toyota RAV4',
    'brand': 'Toyota',
    'category': 'SUV',
    'price': 31999.99,
    'countInStock': 10,
    'rating': 4.8,
    'numReviews': 20,
    'description': 'The Toyota RAV4 is a compact SUV with a reputation for reliability and versatility. It offers a comfortable ride and plenty of cargo space for your adventures.',
    'image': '/images/rav4.jpg',
  },
  {
    '_id': '4',
    'name': 'Mercedes-Benz C-Class',
    'brand': 'Mercedes',
    'category': 'Luxury',
    'price': 43999.99,
    'countInStock': 8,
    'rating': 4.9,
    'numReviews': 25,
    'description': 'The Mercedes-Benz C-Class is a luxury car known for its sophisticated design, advanced technology, and smooth performance.',
    'image': '/images/c-class.jpg',
  },
  {
    '_id': '5',
    'name': 'Mercedes-Benz E-Class',
    'brand': 'Mercedes',
    'category': 'Luxury',
    'price': 56999.99,
    'countInStock': 6,
    'rating': 4.6,
    'numReviews': 22,
    'description': 'The Mercedes-Benz E-Class is a premium luxury sedan with cutting-edge features, a comfortable interior, and powerful performance.',
    'image': '/images/e-class.jpg',
  },
  {
    '_id': '6',
    'name': 'Mercedes-Benz GLE',
    'brand': 'Mercedes',
    'category': 'SUV',
    'price': 68999.99,
    'countInStock': 7,
    'rating': 4.7,
    'numReviews': 18,
    'description': 'The Mercedes-Benz GLE is a luxury SUV that combines elegance with powerful performance, making it a popular choice among SUV enthusiasts.',
    'image': '/images/gle.jpg',
  },
  {
    '_id': '7',
    'name': 'Kia Forte',
    'brand': 'Kia',
    'category': 'Sedan',
    'price': 17999.99,
    'countInStock': 14,
    'rating': 4.4,
    'numReviews': 16,
    'description': 'The Kia Forte is a compact sedan that offers a stylish design, fuel efficiency, and a comfortable interior at an affordable price.',
    'image': '/images/forte.jpg',
  },
  {
    '_id': '8',
    'name': 'Kia Sorento',
    'brand': 'Kia',
    'category': 'SUV',
    'price': 28999.99,
    'countInStock': 11,
    'rating': 4.5,
    'numReviews': 19,
    'description': 'The Kia Sorento is a midsize SUV that provides ample space, advanced safety features, and a smooth ride for families and adventurers alike.',
    'image': '/images/sorento.jpg',
  },
  # Add more cars as needed
]