CREATE USER react_django WITH PASSWORD 'react_django';

GRANT ALL PRIVILEGES ON DATABASE caslab TO react_django;
ALTER ROLE react_django SET search_path TO react_django;


SELECT * FROM auth_user au ;
SELECT * FROM product;

---------------------------------------------20:00------------------------------------------------------
SELECT
    SUBSTR(CAA.FULL_NAME, 1, INSTR(CAA.FULL_NAME, '>') - 1) AS PTES,
    sum(CASE WHEN RELAY_TYPE = 1 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "JAMI O'CHIRILGAN",
    sum(CASE WHEN RELAY_TYPE = 0 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "JAMI YOQILGAN",
    sum(CASE WHEN RELAY_TYPE = 1 AND r.CONSUME_TYPE = 6 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Aholi O'CHIRILGAN",
    sum(CASE WHEN RELAY_TYPE = 0 AND r.CONSUME_TYPE = 6 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Aholi YOQILGAN",
    sum(CASE WHEN RELAY_TYPE = 1 AND CONSUME_TYPE = 1 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Yuridik O'CHIRILGAN",
    sum(CASE WHEN RELAY_TYPE = 0 AND CONSUME_TYPE = 1 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Yuridik YOQILGAN"
FROM
            M_METER_RELAY_CONTROL_TASK_HIS r
LEFT JOIN C_AR_AREA caa ON
            r.AREA_ID = caa.AREA_ID
WHERE
         trunc(r.CREATE_TIME) = date'2023-12-05'
    AND r.area_id IS NOT NULL AND R.OPERATOR IS NOT null
GROUP BY
    SUBSTR(CAA.FULL_NAME, 1, INSTR(CAA.FULL_NAME, '>') - 1)
UNION ALL 
SELECT
    'JAMI',
    sum(CASE WHEN RELAY_TYPE = 1 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "JAMI O'CHIRILGAN",
    sum(CASE WHEN RELAY_TYPE = 0 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "JAMI YOQILGAN",
    sum(CASE WHEN RELAY_TYPE = 1 AND r.CONSUME_TYPE = 6 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Aholi O'CHIRILGAN",
    sum(CASE WHEN RELAY_TYPE = 0 AND r.CONSUME_TYPE = 6 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Aholi YOQILGAN",
    sum(CASE WHEN RELAY_TYPE = 1 AND CONSUME_TYPE = 1 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Yuridik O'CHIRILGAN",
    sum(CASE WHEN RELAY_TYPE = 0 AND CONSUME_TYPE = 1 AND TASK_STATUS = 2 THEN 1 ELSE NULL END) "Yuridik YOQILGAN"
FROM
            M_METER_RELAY_CONTROL_TASK_HIS r
LEFT JOIN C_AR_AREA caa ON
            r.AREA_ID = caa.AREA_ID
WHERE
           trunc(r.CREATE_TIME) = date'2023-12-05'
    AND r.area_id IS NOT NULL AND R.OPERATOR IS NOT null 
GROUP BY 
    'JAMI';


------------------------------------------------------all_reestrdan---------------------------------------------
SELECT d.* FROM viloyatlar_ordered vo LEFT JOIN "data"  d ON vo.cas_ptes =d.ptes ;