# Generated by Django 4.2.7 on 2023-11-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product1_delete_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product1',
            table='Product1',
        ),
    ]
